
###
POST http://localhost:21500/v1.0/api/auth/login HTTP/1.1
Content-Type: application/json
Authorization: b8a820289e6848b6b8ee970fa45abbeb

{
  "asfas":"fasfas"
}

###
GET http://localhost:21500/v1.0/api/certificate HTTP/1.1
Content-Type: application/json
Authorization:Arh 521b1893a90e4c1987dc8d20d9e4ba63

###
POST  https://arh-cv-api.herokuapp.com/djEuMC9hcGkvc2tpbGw.arh HTTP/1.1
Content-Type: application/json

###
POST http://localhost:21500/v1.0/api/auth/updateVisitor HTTP/1.1
Content-Type: application/json
Authorization: Arh 1672ba708c284dd6b04398feefee9dbd

{
   "data":"CWjSywZJiHMGqwrM?xr3ysbsywnM@wfSieEGDq",
   "creator": "Adhitya Rachman H"
}

###

GET  http://localhost:21500/v1.0/api/music  HTTP/1.1
Authorization: Arh eyJ0b2tlbiI6Ijk4OTc0NzViOTczMTQwNTc5OTA3OWQ5NDQ5YjdiYmI1IiwidHlwZSI6InZpc2l0b3JzIn0
###

GET  http://localhost:21500/v1.0/api/projects  HTTP/1.1
Authorization: Arh eyJ0b2tlbiI6Ijk4OTc0NzViOTczMTQwNTc5OTA3OWQ5NDQ5YjdiYmI1IiwidHlwZSI6InZpc2l0b3JzIn0

###
POST http://localhost:21500/v1.0/api/auth/autologin HTTP/1.1
Content-Type: application/json
Authorization: Arh eyJ0b2tlbiI6IjY0MDNmNmNhOTBkMjQ0N2RhNGMzYjMyMzdlMjAzYmZjIiwidHlwZSI6InZpc2l0b3JzIn0

{
  "data":{
    "name": "",
    "chat": false,
    "token": "",
    "ip_address":"122.241.124.124"
  }
}


###
POST https://fcm.googleapis.com/fcm/send HTTP/1.1
Authorization: key=AAAArXzEV5k:APA91bF_zqbLqyE-p_W-ZWRTFXdzlq9Dsq4uOWl9XoqOcDDCqLK2yrTSA6If3DzovLinWAjnHl2tieGdQXLEDXLezbhTSl4mb0dOWzLSw9FmttMtQMKxO5IRESggsFa78JyP3vQOnDQj
Content-Type: application/json

{
  "notification": {
    "title": "Hey there", 
    "body": "Subscribe to mighty ghost hack youtube channel"
  },
  "to" : "e9uzmr2mG6mudqLB2DUukM:APA91bELyIYn-WXg_b1yHMxXkdGndouSnmKHjyXOU6xxZcypvoxgE18p2KXVWXFNei3829NQzDhyZZNrSQURaUyAk27v0K7dRei9CmyLMDRIx761A65b-sauH11pXPhlCW6_gx7GOyfx"
}

###
POST  http://localhost:21500/v1.0/api/admin/auth/login HTTP/1.1
Content-Type: application/json
Authorization: Arh eyJ0b2tlbiI6ImM3NGExOTZmLWYxOWQtNWVhOS1iZmZkLWEyNzQyNDMyZmM5YyIsInR5cGUiOiJhZG1pbnMifQ

{
  "data":{
    "username":"adhityarachmanh",
    "password":""
  },
  "creator":"Adhitya Rachman H"

}

###
POST  http://localhost:21500/v1.0/api/admin/auth/autologin HTTP/1.1
Content-Type: application/json
Authorization: Arh eyJ0b2tlbiI6ImM3NGExOTZmLWYxOWQtNWVhOS1iZmZkLWEyNzQyNDMyZmM5YyIsInR5cGUiOiJhZG1pbnMifQ


{
  "data":""
}
